// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
)

type Querier interface {
	CheckUserExist(ctx context.Context, email string) (bool, error)
	CreateNewUser(ctx context.Context, arg CreateNewUserParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
